name: Hook Essential Coverage

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list files
      run: npm install ./package.json
    - name: Install NPM packages
      run: npm install
    - name: Create Coverage Report
      run: npm run coverage
