name: Hook Essential Coverage

on: push

jobs:

  build:

    runs-on: node

    steps:
    - uses: actions/checkout@v2
    - name: Update NPM
      run:  npm install -g npm@latest
    - name: NPM Version
      run:  npm --version
    - name: Install NPM packages
      run: npm install
    - name: list packages
      run: npm list --depth=0
    - name: Create Coverage Report
      run: npm run coverage
